AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Gmail Agentic AI App

Resources:
  GmailPollingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: gmail-polling-agent
      Handler: main.lambda_handler
      Runtime: python3.13
      Timeout: 120
      MemorySize: 512
      CodeUri: src/email_retrieval_lambda/
      Events:
        PollGmail:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
      Environment:
        Variables:
          AGENT_FUNCTION: !Ref TriageAgent
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt TriageAgent.Arn
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:767828762541:secret:GmailCreds-9VnUhM 
  TriageAgent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: triage-agent
      Handler: main.lambda_handler
      Runtime: python3.13
      Timeout: 600
      MemorySize: 512
      CodeUri: src/triage_agent_lambda/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:767828762541:secret:Google_Gemini_flash-2.0_key-mKd1EN
        - DynamoDBCrudPolicy:
            TableName: StructuredUserProfiles
        - DynamoDBCrudPolicy:
            TableName: UserProfiles
        - DynamoDBCrudPolicy:
            TableName: ScoredEmails
  EditUserProfile:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: edit-user-profile
      Handler: main.lambda_handler
      Runtime: python3.13
      Timeout: 600
      MemorySize: 512
      CodeUri: src/edit_user_profile_lambda/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:767828762541:secret:Google_Gemini_flash-2.0_key-mKd1EN
        - DynamoDBCrudPolicy:
            TableName: StructuredUserProfiles
        - DynamoDBCrudPolicy:
            TableName: UserProfiles
      Events:
        UpdateUserProfile:
          Type: HttpApi
          Properties:
            Path: /profile
            Method: POST


  ScoredEmailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ScoredEmails
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_email
          AttributeType: S
        - AttributeName: score
          AttributeType: N
      KeySchema:
        - AttributeName: user_email
          KeyType: HASH
        - AttributeName: score
          KeyType: RANGE
  StructuredUserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StructuredUserProfiles
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_email
          AttributeType: S
      KeySchema:
        - AttributeName: user_email
          KeyType: HASH
  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserProfiles
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_email
          AttributeType: S
      KeySchema:
        - AttributeName: user_email
          KeyType: HASH