AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Gmail Agentic AI App

Resources:
  GmailPollingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: gmail-polling-agent
      Handler: email_retrieval.lambda_handler
      Runtime: python3.13
      Timeout: 120
      MemorySize: 512
      CodeUri: .
      Events:
        PollGmail:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Environment:
        Variables:
          AGENT_FUNCTION: !Ref TriageAgent
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt TriageAgent.Arn
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:767828762541:secret:GmailCreds-9VnUhM 
  TriageAgent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: triage-agent
      Handler: agent_entry.lambda_handler
      Runtime: python3.13
      Timeout: 600
      MemorySize: 512
      CodeUri: .
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:767828762541:secret:Google_Gemini_flash-2.0_key-mKd1EN